server:
  context-path: /springboot
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: huating.biz.entity

